/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
});
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'nickName' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : Time,
  'contactPrincipal' : IDL.Principal,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'userPrincipal' : IDL.Principal,
  'message' : IDL.Text,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
});
export const BorrowLendRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
  'respondedAt' : IDL.Opt(Time),
  'requestType' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'requestId' : IDL.Text,
  'transactionType' : IDL.Text,
  'createdAt' : Time,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRequest' : IDL.Func(
      [IDL.Principal, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalLent' : IDL.Float64,
          'pendingRequests' : IDL.Nat,
          'totalBorrowed' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMyContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyProfile' : IDL.Func([], [User], ['query']),
  'getMyRequests' : IDL.Func(
      [],
      [
        IDL.Record({
          'sent' : IDL.Vec(BorrowLendRequest),
          'received' : IDL.Vec(BorrowLendRequest),
        }),
      ],
      ['query'],
    ),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Text], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Text], []),
  'registerOrUpdateProfile' : IDL.Func([IDL.Text], [IDL.Text], []),
  'respondToRequest' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
  });
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'nickName' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : Time,
    'contactPrincipal' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'userPrincipal' : IDL.Principal,
    'message' : IDL.Text,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
  });
  const BorrowLendRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
    'respondedAt' : IDL.Opt(Time),
    'requestType' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'requestId' : IDL.Text,
    'transactionType' : IDL.Text,
    'createdAt' : Time,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRequest' : IDL.Func(
        [IDL.Principal, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalLent' : IDL.Float64,
            'pendingRequests' : IDL.Nat,
            'totalBorrowed' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMyContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyProfile' : IDL.Func([], [User], ['query']),
    'getMyRequests' : IDL.Func(
        [],
        [
          IDL.Record({
            'sent' : IDL.Vec(BorrowLendRequest),
            'received' : IDL.Vec(BorrowLendRequest),
          }),
        ],
        ['query'],
      ),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Text], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Text], []),
    'registerOrUpdateProfile' : IDL.Func([IDL.Text], [IDL.Text], []),
    'respondToRequest' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };