/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BorrowLendRequest {
  'id' : string,
  'status' : RequestStatus,
  'createdAt' : Time,
  'description' : string,
  'toPrincipal' : Principal,
  'updatedAt' : Time,
  'fromPrincipal' : Principal,
  'amount' : number,
  'requestType' : RequestType,
}
export interface Contact { 'principal' : Principal, 'addedAt' : Time }
export interface Notification {
  'id' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'read' : boolean,
  'relatedRequestId' : [] | [string],
  'message' : string,
}
export type RequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type RequestType = { 'lend' : null } |
  { 'borrow' : null };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'completedAt' : Time,
  'requestId' : string,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'amount' : number,
  'requestType' : RequestType,
}
export interface UserProfile {
  'displayName' : string,
  'createdAt' : Time,
  'email' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRequest' : ActorMethod<
    [Principal, RequestType, number, string],
    string
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getDashboardSummary' : ActorMethod<
    [],
    { 'pendingCount' : bigint, 'totalOwe' : number, 'totalOwedToMe' : number }
  >,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyRequests' : ActorMethod<[], Array<BorrowLendRequest>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getRequestById' : ActorMethod<[string], [] | [BorrowLendRequest]>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isContact' : ActorMethod<[Principal], boolean>,
  'isProfileComplete' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markCompleted' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'registerProfile' : ActorMethod<[string, string, string], undefined>,
  'removeContact' : ActorMethod<[Principal], undefined>,
  'respondToRequest' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchContactByMobileOrEmail' : ActorMethod<
    [string],
    Array<[Principal, UserProfile]>
  >,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];