/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'lend' : IDL.Null,
  'borrow' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Contact = IDL.Record({
  'principal' : IDL.Principal,
  'addedAt' : Time,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'read' : IDL.Bool,
  'relatedRequestId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const BorrowLendRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'createdAt' : Time,
  'description' : IDL.Text,
  'toPrincipal' : IDL.Principal,
  'updatedAt' : Time,
  'fromPrincipal' : IDL.Principal,
  'amount' : IDL.Float64,
  'requestType' : RequestType,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : Time,
  'requestId' : IDL.Text,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'amount' : IDL.Float64,
  'requestType' : RequestType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRequest' : IDL.Func(
      [IDL.Principal, RequestType, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingCount' : IDL.Nat,
          'totalOwe' : IDL.Float64,
          'totalOwedToMe' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(BorrowLendRequest)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getRequestById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BorrowLendRequest)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isContact' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markCompleted' : IDL.Func([IDL.Text], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'registerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeContact' : IDL.Func([IDL.Principal], [], []),
  'respondToRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchContactByMobileOrEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestType = IDL.Variant({ 'lend' : IDL.Null, 'borrow' : IDL.Null });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Contact = IDL.Record({ 'principal' : IDL.Principal, 'addedAt' : Time });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'relatedRequestId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const BorrowLendRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'createdAt' : Time,
    'description' : IDL.Text,
    'toPrincipal' : IDL.Principal,
    'updatedAt' : Time,
    'fromPrincipal' : IDL.Principal,
    'amount' : IDL.Float64,
    'requestType' : RequestType,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : Time,
    'requestId' : IDL.Text,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'amount' : IDL.Float64,
    'requestType' : RequestType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRequest' : IDL.Func(
        [IDL.Principal, RequestType, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingCount' : IDL.Nat,
            'totalOwe' : IDL.Float64,
            'totalOwedToMe' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(BorrowLendRequest)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getRequestById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BorrowLendRequest)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isContact' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markCompleted' : IDL.Func([IDL.Text], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'registerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeContact' : IDL.Func([IDL.Principal], [], []),
    'respondToRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchContactByMobileOrEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };