/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BorrowLendRequest {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'notes' : string,
  'amount' : number,
  'respondedAt' : [] | [Time],
  'requestType' : string,
}
export interface Contact {
  'id' : string,
  'nickName' : string,
  'ownerPrincipal' : Principal,
  'createdAt' : Time,
  'contactPrincipal' : Principal,
}
export interface Notification {
  'id' : string,
  'createdAt' : Time,
  'isRead' : boolean,
  'userPrincipal' : Principal,
  'message' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'requestId' : string,
  'transactionType' : string,
  'createdAt' : Time,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'amount' : number,
}
export interface User {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : Time,
  'isActive' : boolean,
}
export interface UserProfile {
  'displayName' : string,
  'name' : string,
  'createdAt' : Time,
  'isActive' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[Principal, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRequest' : ActorMethod<[Principal, number, string, string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<
    [],
    {
      'totalLent' : number,
      'pendingRequests' : bigint,
      'totalBorrowed' : number,
    }
  >,
  'getMyContacts' : ActorMethod<[], Array<Contact>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], User>,
  'getMyRequests' : ActorMethod<
    [],
    { 'sent' : Array<BorrowLendRequest>, 'received' : Array<BorrowLendRequest> }
  >,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], string>,
  'markNotificationRead' : ActorMethod<[string], string>,
  'registerOrUpdateProfile' : ActorMethod<[string], string>,
  'respondToRequest' : ActorMethod<[string, boolean], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];